packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  ejs: true
  es5-ext: true
  esbuild: true
  fsevents: true
  husky: true

patchedDependencies:
  lodestar-app-element@0.1.0: patches/lodestar-app-element@0.1.0.patch
