export type ProductType =
  | 'ProgramPlan'
  | 'ProgramContent'
  | 'ProgramPackagePlan'
  | 'ProjectPlan'
  | 'Card'
  | 'ActivityTicket'
  | 'Merchandise'
  | 'MerchandiseSpec'
  | 'PodcastProgram'
  | 'PodcastPlan'
  | 'AppointmentPlan'
