name: Deploy to S3

on:
  push:
    branches:
      - release
      - master

env:
  NODE_ENV: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_REGION: us-east-1
          AWS_S3_BUCKET: ${{ github.ref == 'refs/heads/master' && 'static.kolable.com' || 'static-dev.kolable.com' }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: build
          DEST_DIR: deploys/${{ github.repository }}/${{ github.ref }}

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
