name: Mirror to GitLab

on:
  push:
    branches:
      - master
      - release
      - develop

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Push current branch to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://gitlab+deploy-token-13469759:${GITLAB_TOKEN}@gitlab.com/urfit/lodestar/app.git
          git push gitlab HEAD:${GITHUB_REF_NAME}
